<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class RatingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('ratings')->insert([
            'rating'=>'5',
            'rateable_type'=>'App\Models\Reteta',
            'rateable_id'=>'15',
            'user_id'=>'1'
        ]);
        DB::table('ratings')->insert([
            'rating'=>'3',
            'rateable_type'=>'App\Models\Reteta',
            'rateable_id'=>'15',
            'user_id'=>'4'
        ]);
        DB::table('ratings')->insert([
            'rating'=>'1',
            'rateable_type'=>'App\Models\Reteta',
            'rateable_id'=>'15',
            'user_id'=>'5'
        ]);
        DB::table('ratings')->insert([
            'rating'=>'3',
            'rateable_type'=>'App\Models\Reteta',
            'rateable_id'=>'15',
            'user_id'=>'2'
        ]);
        DB::table('ratings')->insert([
            'rating'=>'4',
            'rateable_type'=>'App\Models\Reteta',
            'rateable_id'=>'15',
            'user_id'=>'6'
        ]);
        DB::table('ratings')->insert([
            'rating'=>'4',
            'rateable_type'=>'App\Models\Reteta',
            'rateable_id'=>'15',
            'user_id'=>'7'
        ]);
        DB::table('ratings')->insert([
            'rating'=>'3',
            'rateable_type'=>'App\Models\Reteta',
            'rateable_id'=>'15',
            'user_id'=>'8'
        ]);
        DB::table('ratings')->insert([
            'rating'=>'3',
            'rateable_type'=>'App\Models\Reteta',
            'rateable_id'=>'15',
            'user_id'=>'9'
        ]);
        DB::table('ratings')->insert([
            'rating'=>'2',
            'rateable_type'=>'App\Models\Reteta',
            'rateable_id'=>'15',
            'user_id'=>'10'
        ]);
        DB::table('ratings')->insert([
            'rating'=>'5',
            'rateable_type'=>'App\Models\Reteta',
            'rateable_id'=>'15',
            'user_id'=>'11'
        ]);
        DB::table('ratings')->insert([
            'rating'=>'5',
            'rateable_type'=>'App\Models\Reteta',
            'rateable_id'=>'14',
            'user_id'=>'11'
        ]);
        DB::table('ratings')->insert([
            'rating'=>'3',
            'rateable_type'=>'App\Models\Reteta',
            'rateable_id'=>'14',
            'user_id'=>'12'
        ]);
        DB::table('ratings')->insert([
            'rating'=>'1',
            'rateable_type'=>'App\Models\Reteta',
            'rateable_id'=>'14',
            'user_id'=>'10'
        ]);
        DB::table('ratings')->insert([
            'rating'=>'5',
            'rateable_type'=>'App\Models\Reteta',
            'rateable_id'=>'14',
            'user_id'=>'8'
        ]);
        DB::table('ratings')->insert([
            'rating'=>'3',
            'rateable_type'=>'App\Models\Reteta',
            'rateable_id'=>'14',
            'user_id'=>'7'
        ]);
        DB::table('ratings')->insert([
            'rating'=>'2',
            'rateable_type'=>'App\Models\Reteta',
            'rateable_id'=>'14',
            'user_id'=>'6'
        ]);
    }
}
